# Generated by Django 4.2.7 on 2024-02-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='syllabus',
            new_name='syllabusupload',
        ),
    ]
