# Generated by Django 4.2.7 on 2024-02-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_syllabus_syllabusupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffreg',
            name='username',
        ),
    ]
