# Generated by Django 4.2.7 on 2024-02-03 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_staffreg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentreg')),
            ],
        ),
    ]
