# Generated by Django 4.2.7 on 2024-02-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_companies_replaying_for_contact_allocatestudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaying_for_contact',
            name='student',
        ),
        migrations.DeleteModel(
            name='allocatestudent',
        ),
        migrations.DeleteModel(
            name='companies',
        ),
        migrations.DeleteModel(
            name='replaying_for_contact',
        ),
    ]
