# Generated by Django 4.2.7 on 2024-02-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocatestudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(default='', max_length=200)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentreg')),
            ],
        ),
    ]
