# Generated by Django 4.2.7 on 2024-02-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_allocatestudent_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('industry', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='placementcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Please enter a valid email address.', max_length=254, unique=True)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='replaying_for_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_message', models.TextField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentreg')),
            ],
        ),
        migrations.CreateModel(
            name='allocatestudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(default='', max_length=200)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('department_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentreg')),
            ],
        ),
    ]
