# Generated by Django 4.2.7 on 2024-02-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_staffapplyleave_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_feedback',
            name='staff',
        ),
    ]
