# Generated by Django 4.2.7 on 2024-02-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_staff_feedback_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_feedback',
            name='student',
        ),
    ]
