# Generated by Django 4.2.7 on 2024-02-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_stud_feedback_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_applyleave',
            name='student',
        ),
    ]
