# Generated by Django 4.2.7 on 2024-02-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_stud_applyleave_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplyleave',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.studentreg'),
        ),
    ]
