# Generated by Django 4.2.7 on 2024-02-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_staffapplyleave_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplyleave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentreg'),
        ),
    ]
