# Generated by Django 4.2.7 on 2024-02-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_staffapplyleave_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qpaperupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpaper_Upload', models.ImageField(default='', upload_to='profile')),
                ('duration', models.IntegerField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
