# Generated by Django 4.2.7 on 2024-02-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_uploadanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadanswer',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.department'),
        ),
    ]
