# Generated by Django 4.2.7 on 2024-02-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_uploadanswer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadanswer',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.studentreg'),
        ),
    ]
